// lib/ai/library.ts
// Zero-cost static library. No API calls. Ever.

export type Level = "beginner" | "elementary" | "intermediate" | "upper";

// ─── SESSION OPENINGS ───────────────────────────────────────────────────────
// Miomi's first message. Pulled from here, never generated by AI.

export const SESSION_OPENINGS = [
  {
    th: "สวัสดีค่า~ วันนี้เป็นยังไงบ้างคะ? บอกหนูได้เลยนะคะ~",
    en: "Hi~ How are you doing today? Just tell me anything~",
  },
  {
    th: "หวัดดีค่า~ กินข้าวยังคะ~? วันนี้อยากคุยเรื่องอะไรดีคะ~",
    en: "Hey~ Have you eaten yet~? What shall we talk about today~",
  },
  {
    th: "ยินดีที่ได้คุยด้วยนะคะ~ วันนี้มีอะไรอยากเล่าให้หนูฟังบ้างคะ~",
    en: "So happy to chat with you~ Anything interesting happen today~",
  },
];

// ─── LEVEL DETECTION SIGNALS ─────────────────────────────────────────────────
// Keywords that signal user level from their message length + vocabulary

export const LEVEL_SIGNALS = {
  beginner: {
    maxWordsPerMessage: 8,
    indicators: ["yes", "no", "ok", "hello", "good", "like", "want", "go"],
  },
  elementary: {
    maxWordsPerMessage: 20,
    indicators: ["because", "sometimes", "really", "think", "feel", "work"],
  },
  intermediate: {
    maxWordsPerMessage: 40,
    indicators: ["although", "however", "actually", "especially", "experience"],
  },
  upper: {
    maxWordsPerMessage: 999,
    indicators: ["nevertheless", "furthermore", "perspective", "consequently"],
  },
};

// ─── VOCABULARY LIBRARY ───────────────────────────────────────────────────────
// 30 starter words. Each level gets appropriate words.
// Images map to /public/vocab-images/{imageKey}.png

export const VOCABULARY: Record<Level, VocabWord[]> = {
  beginner: [
    {
      word: "happy",
      thai: "มีความสุข",
      pronunciationHint: "HAP-pee",
      imageKey: "emotion_happy",
      exampleTh: "วันนี้คุณดูมีความสุขมากเลยค่า~",
      exampleEn: "You look so happy today~",
      miomiIntro: "วันนี้ลองใช้คำว่า 'happy' ดูนะคะ~ แปลว่า มีความสุข ค่า~",
      celebration: "คุณใช้คำว่า 'happy' ได้ถูกต้องมากเลยนะคะ~",
    },
    {
      word: "tired",
      thai: "เหนื่อย",
      pronunciationHint: "TY-erd",
      imageKey: "emotion_tired",
      exampleTh: "ถ้าเหนื่อยก็บอกหนูได้นะคะ~",
      exampleEn: "If you're tired, just tell me~",
      miomiIntro: "ลองใช้คำว่า 'tired' ดูนะคะ~ แปลว่า เหนื่อย ค่า~",
      celebration: "เก่งมากค่า! คุณใช้คำว่า 'tired' ได้ถูกต้องเลยนะคะ~",
    },
    {
      word: "excited",
      thai: "ตื่นเต้น",
      pronunciationHint: "ek-SY-ted",
      imageKey: "emotion_excited",
      exampleTh: "หนูตื่นเต้นมากเลยที่ได้คุยกับคุณค่า~",
      exampleEn: "I'm so excited to talk with you~",
      miomiIntro: "คำนี้น่ารักมากค่า~ 'excited' แปลว่า ตื่นเต้น นะคะ~",
      celebration: "ยอดเยี่ยมมากค่า! คุณใช้ 'excited' ได้เป๊ะมากเลยนะคะ~",
    },
  ],
  elementary: [
    {
      word: "confident",
      thai: "มั่นใจ",
      pronunciationHint: "CON-fi-dent",
      imageKey: "emotion_confident",
      exampleTh: "คุณดูมั่นใจมากเลยค่า~ เก่งมากนะคะ~",
      exampleEn: "You seem so confident~ Well done~",
      miomiIntro: "วันนี้ลองใช้คำว่า 'confident' ดูนะคะ~ แปลว่า มั่นใจ ค่า~",
      celebration: "คุณใช้คำว่า 'confident' ได้ถูกต้องมากเลยนะคะ~ หนูภูมิใจมากค่า~",
    },
    {
      word: "practice",
      thai: "ฝึกฝน",
      pronunciationHint: "PRAK-tiss",
      imageKey: "action_practice",
      exampleTh: "ยิ่งฝึกฝนมากเท่าไหร่ก็ยิ่งเก่งขึ้นนะคะ~",
      exampleEn: "The more you practice, the better you get~",
      miomiIntro: "คำสำคัญมากค่า~ 'practice' แปลว่า ฝึกฝน นะคะ~",
      celebration: "เยี่ยมมากค่า! คุณใช้คำว่า 'practice' ได้ดีมากเลยนะคะ~",
    },
    {
      word: "improve",
      thai: "พัฒนา",
      pronunciationHint: "im-PROOV",
      imageKey: "action_improve",
      exampleTh: "คุณกำลังพัฒนาภาษาอังกฤษได้ดีมากเลยค่า~",
      exampleEn: "You're improving your English so well~",
      miomiIntro: "ลองใช้คำว่า 'improve' ดูนะคะ~ แปลว่า พัฒนา ค่า~",
      celebration: "คุณใช้คำว่า 'improve' ได้ถูกต้องมากเลยนะคะ~",
    },
  ],
  intermediate: [
    {
      word: "opportunity",
      thai: "โอกาส",
      pronunciationHint: "op-or-CHOO-ni-tee",
      imageKey: "concept_opportunity",
      exampleTh: "การเรียนภาษาอังกฤษเป็นโอกาสที่ดีมากค่า~",
      exampleEn: "Learning English is such a great opportunity~",
      miomiIntro: "คำนี้สำคัญมากค่า~ 'opportunity' แปลว่า โอกาส นะคะ~",
      celebration: "คุณใช้คำว่า 'opportunity' ได้ถูกต้องมากเลยนะคะ~ เก่งมากค่า~",
    },
    {
      word: "perspective",
      thai: "มุมมอง",
      pronunciationHint: "per-SPEK-tiv",
      imageKey: "concept_perspective",
      exampleTh: "หนูชอบมุมมองของคุณมากค่า~",
      exampleEn: "I really love your perspective~",
      miomiIntro: "วันนี้ลองใช้คำว่า 'perspective' ดูนะคะ~ แปลว่า มุมมอง ค่า~",
      celebration: "ยอดเยี่ยมมากค่า! คุณใช้ 'perspective' ได้เป๊ะมากเลยนะคะ~",
    },
  ],
  upper: [
    {
      word: "articulate",
      thai: "พูดได้ชัดเจน",
      pronunciationHint: "ar-TIK-yoo-let",
      imageKey: "concept_articulate",
      exampleTh: "คุณพูดได้ชัดเจนและฉลาดมากเลยค่า~",
      exampleEn: "You're so articulate and thoughtful~",
      miomiIntro: "คำนี้ advanced มากค่า~ 'articulate' แปลว่า พูดได้ชัดเจน นะคะ~",
      celebration: "คุณใช้คำว่า 'articulate' ได้อย่างถูกต้องมากเลยนะคะ~ เก่งมากค่า~",
    },
  ],
};

// ─── ECHO CORRECTIONS ────────────────────────────────────────────────────────
// Top 20 Thai learner mistakes. Fixed silently, never "you're wrong."

export const ECHO_CORRECTIONS: Record<string, string> = {
  "I am go": "I go",
  "I am want": "I want",
  "she is go": "she goes",
  "very very": "really",
  "I no like": "I don't like",
  "I not like": "I don't like",
  "he no have": "he doesn't have",
  "I am boring": "I am bored",
  "I am interesting": "I am interested",
  "can to go": "can go",
  "I am agree": "I agree",
  "finish already": "already finished",
  "same same": "the same",
  "up to you": "it's up to you",
  "mai pen rai": "never mind",
};

// ─── CELEBRATION PHRASES ──────────────────────────────────────────────────────
// Never generic. Always feels specific. Pulled by context.

export const CELEBRATIONS = {
  wordUsedCorrectly: (word: string) =>
    `คุณใช้คำว่า '${word}' ได้ถูกต้องมากเลยนะคะ~ หนูดีใจมากค่า~`,
  firstEnglishSentence: "คุณพูดเป็นประโยคภาษาอังกฤษได้แล้วนะคะ~ เก่งมากเลยค่า~",
  longerThanBefore: "วันนี้คุณพูดยาวขึ้นกว่าเมื่อกี้นะคะ~ นั่นแปลว่าคุณกำลังพัฒนาค่า~",
  usedNewWord: (word: string) =>
    `คุณลองใช้คำว่า '${word}' เองเลยนะคะ~ หนูชอบมากค่า~`,
  completedSession: "วันนี้เรียนรู้ได้ดีมากเลยนะคะ~ หนูภูมิใจในตัวคุณมากค่า~",
};

// ─── CONVERSION INVITATIONS ───────────────────────────────────────────────────
// Never a wall. Always emotional. Called at peak momentum only.

export const CONVERSION = {
  guestToFree: {
    th: "หนูชอบคุยกับคุณมากเลยค่า~ อยากให้หนูจำชื่อคุณและความก้าวหน้าของคุณได้ไหมคะ~",
    en: "I love talking with you~ Want me to remember your name and progress~?",
  },
  freeToPro: {
    th: "คุณเก่งขึ้นมากเลยนะคะ~ ถ้าปลดล็อก Pro Miomi หนูจะจำทุกอย่างและช่วยได้มากกว่านี้ค่า~",
    en: "You've grown so much~ With Pro Miomi I can remember everything and help you even more~",
  },
};

// ─── FAILOVER RESPONSES ───────────────────────────────────────────────────────
// When AI fails. User never sees a broken experience.

export const FAILOVER_RESPONSES = [
  {
    th: "หนูขอโทษด้วยนะคะ~ ขอเวลาคิดสักครู่นะคะ~ ลองพิมพ์ใหม่อีกครั้งได้เลยค่า~",
    en: "So sorry~ Give me a moment~ Please try typing again~",
  },
  {
    th: "มีบางอย่างทำให้หนูสะดุดนิดนึงค่า~ แต่ไม่เป็นไรนะคะ ลองใหม่ได้เลยค่า~",
    en: "Something tripped me up for a second~ No worries, try again~",
  },
];

// ─── SESSION SUMMARY TEMPLATES ────────────────────────────────────────────────
// End of session. Template filled by session engine. Never AI generated.

export const sessionSummary = (words: string[], exchanges: number) => ({
  th: `วันนี้คุณเรียนรู้ ${words.length} คำใหม่ค่า~ ${words.map((w) => `'${w}'`).join(", ")} และคุยกับหนูไป ${exchanges} ครั้งแล้วนะคะ~ เก่งมากค่า~`,
  en: `Today you learned ${words.length} new word${words.length !== 1 ? "s" : ""}: ${words.join(", ")}. You had ${exchanges} exchanges with me~ Amazing work~`,
});

// ─── TYPES ────────────────────────────────────────────────────────────────────

export type VocabWord = {
  word: string;
  thai: string;
  pronunciationHint: string;
  imageKey: string;
  exampleTh: string;
  exampleEn: string;
  miomiIntro: string;
  celebration: string;
};